import React from 'react';
import styled from 'styled-components';
import { BsFacebook } from 'react-icons/bs';

function Facebook({ selectedStyle, productName }) {
  const styleName = selectedStyle.name.replace('&', 'and');

  const facebookPost = `Look what I just found! It's
  ${styleName} ${productName} you can find here on Nile.
  This message was automatically generated by a share button on a website I am working on
  with a team of awesome and talented fellow student developers, so you can safely ignore this post
  and any others like it if/when I run more tests. Have a great day!`;

  const baseUrl = 'http://www.facebook.com/sharer/sharer.php';
  const linkToShare = '?u=http.cat';

  const fullUrl = baseUrl + linkToShare;

  return (
    <FacebookIcon>
      <a href={fullUrl} target="_blank" rel="noreferrer">
        <BsFacebook size={25} color="#4267B2" />
      </a>
    </FacebookIcon>
  );
}

const FacebookIcon = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  margin-bottom: 5px;
`;

export default Facebook;

// window.FB.ui({
//   method: 'feed',
//   link: 'http.cat/',
// }, (response) => {
//   if (response && !response.error_message) {
//     alert('Posting completed.');
//   } else {
//     alert('Error while posting.');
//   }
// });
